import enum

class newCampaignsColumnMap(enum.IntEnum):
    CAMPAIGN_ALIAS = 0,
    CAMPAIGN_UPLOAD_STATUS = 1,
    CAMPAIGN_NAME = 2,
    CAMPAIGN_BUDGET = 3,
    BUDGET_DELIVERY_METHOD = 4,
    CAMPAIGN_STATUS = 5,
    BIDDING_STRATEGY = 6,
    CAMPAIGN_TARGET_ROAS = 7,
    CAMPAIGN_TARGET_CPA = 8,
    CUSTOMER_START_DATE = 9,
    CUSTOMER_END_DATE = 10,
    CUSTOMER_ID = 11,
    ERROR_MESSAGE =12