import enum

class newCampaignsColumnMap(enum.IntEnum):
    CAMPAIGN_ALIAS = 0,
    CAMPAIGN_UPLOAD_STATUS = 1,
    CAMPAIGN_BUDGET = 2,
    BUDGET_DELIVERY_METHOD = 3,
    CAMPAIGN_STATUS = 4,
    BIDDING_STRATEGY = 5,
    CAMPAIGN_TARGET_ROAS = 6,
    CAMPAIGN_TARGET_CPA = 7,
    CUSTOMER_START_DATE = 8,
    CUSTOMER_END_DATE = 9,
    CUSTOMER_ID = 10,
    ERROR_MESSAGE =11